# Generated by Django 4.1.1 on 2022-12-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paymentStatus',
            field=models.BooleanField(default='exit'),
            preserve_default=False,
        ),
    ]
