# Generated by Django 4.1.1 on 2022-12-11 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_user_paymentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='paymentStatus',
        ),
    ]
